name: ceco-lad-cloud
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - backcall=0.2.0
  - ca-certificates=2025.10.5
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=2.1.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.8.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.20
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.16
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.8.20
  - python_abi=3.8
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - readline=8.2
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
